spring.application.name=Kanban_board
# ==============================
# DataSource - MySQL
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/kanban_board?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT
# ==============================
app.jwt.secret=your_super_secret_key_at_least_256_bits_long_change_in_production
app.jwt.expiration-ms=86400000  git remote set-url origin git@github.com:kalanahapuarachchi309-cmd/kanban-project-backend.git
git push origin main

# ==============================
# Cloudinary
# ==============================
cloudinary.cloud-name=djsdwv2na
cloudinary.api-key=216632618736747
cloudinary.api-secret=Bnfp7Px9C57hfxcXrdo2xYx26LY

# ==============================
# Email (SMTP / Gmail App Password)
# ==============================
app.email.from=hapuarachchi.thilak@gmail.com
app.frontend-url=http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hapuarachchi.thilak@gmail.com
spring.mail.password=sekv kxgf gqbq rzig
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==============================
# Server
# ==============================
server.port=8080

# ==============================
# Multipart Upload
# ==============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
